<?php
/**
 * @file
 * Code for the UNFI Import SRM Assignments module.
 */

// Need this in order to ensure we can reference the same tables declared in the install file.
include_once drupal_get_path('module', 'unfi_import_rcm_categories') . '/unfi_import_rcm_categories.install';

/**
 * Implements hook_menu()
 */
function unfi_import_rcm_categories_menu() {

  $items = array();

  // Create the main settings page.
  $items['admin/config/unfi_import/rcm_categories'] = array(
    'title' => t('Import RCM Categories'),
    'description' => t('Upload a .csv file to update the RCM Category taxonomy.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('unfi_import_rcm_categories_upload_form'),
    'access arguments' => array('unfi import data'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Upload form that allows the user to submit a .csv file for processing.
 */
function unfi_import_rcm_categories_upload_form() {

  $example = unfi_import_generate_example(unfi_import_rcm_categories_fetch_tables());

  $form['csv_file'] = array(
    '#type' => 'file',
    '#title' => t('Comma Separated File'),
    '#description' => t('File must be in .csv format.') . $example,
  );

  $form['delimiter'] = array(
    '#type' => 'select',
    '#title' => t('Delimiter'),
    '#options' => array(
      'comma' => 'comma ,',
      'tab' => 'tab \t',
      'pipe' => 'pipe |',
    ),
    '#description' => t('Delimiter of the data file.'),
    '#default_value' => 'comma',
    '#required' => false,
  );

  $form['contains_header'] = array(
    '#type' => 'checkbox',
    '#title' => t('File contains a header'),
    '#description' => t('Skip the first line because it is a header.'),
    '#default_value' => FALSE,
  );

  $form['#attributes']['enctype'] = 'multipart/form-data';

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Upload Data'),
  );

  return $form;
}

function unfi_import_rcm_categories_upload_form_validate($form, &$form_state) {

  $file = file_save_upload('csv_file', array(
    'file_validate_extensions' => array('csv txt'),
  ));
  if ($file) {
    if ($file = file_move($file, 'public://tmp/')) {
      $form_state['values']['csv_file'] = $file;
    }
    else {
      form_set_error('csv_file', t('Failed to write the uploaded file the site\'s tmp folder.'));
    }
  }
  else {
    form_set_error('csv_file', t('No file was uploaded.'));
  }
}

function unfi_import_rcm_categories_upload_form_submit($form, &$form_state) {

  $file = $form_state['values']['csv_file'];

  if(!empty($file->uri)) {
    if(file_exists($file->uri)) {
      unfi_import_rcm_categories_import_data($file->uri, $form_state['values']['contains_header'], $form_state['values']['delimiter']);
    }
  }
}

//read the csv file into the database
function unfi_import_rcm_categories_import_data($file_path, $contains_header=TRUE, $delimiter=',') {
  set_time_limit(300);

  $auto_detect_line_endings = ini_get('auto_detect_line_endings');
  ini_set('auto_detect_line_endings', TRUE);

  // todo: create settings page to configure this.
  $vocab = taxonomy_vocabulary_machine_name_load('rcm_category');

  //read records from the csv file
  $handle = fopen($file_path, 'r');

  $header_row_check = 0;

  $tables =  unfi_import_rcm_categories_fetch_tables();

  // Prep the tables for import.
  unfi_import_prepare_tables($tables);

  // todo: ideally would have some validation here to make sure the columns in the file match what is expected.

  $delimiter = unfi_import_convert_delimiter($delimiter);

  // Load into staging table.
  while (($row = fgetcsv($handle, 0, $delimiter, '"')) !== FALSE) {
    // skip the header line if the form was told to expect a header.
    if($contains_header && $header_row_check == 0) {
      $header_row_check++;
      continue;
    }

    // Check that data matches expected format.
    if (empty($row[0]) || empty($row[2]) || !is_numeric($row[0])) {
      continue;
    }

    foreach ($tables as $table_name => $table_info) {
      unfi_import_insert_record($table_name, $table_info['fields'], $row);
    }
  }

  ini_set('auto_detect_line_endings', $auto_detect_line_endings);

  // #### PROCESS ####

  $msg = 'CSV Uploaded<br/>';

  // Update the staging table with SIDs for syncing to the terms.
  $sql = "UPDATE unfi_import_rcm_categories
          SET department_sid = retail_dept_nm,
          category_sid = CONCAT(retail_dept_nm, '|', retail_cat_nm),
          segment_sid = CONCAT(retail_dept_nm, '|', retail_cat_nm, '|', retail_segment_nm),
          subsegment_sid = CONCAT(retail_dept_nm, '|', retail_cat_nm, '|', retail_segment_nm, '|', retail_subsegment_nm)";
  db_query($sql)->execute();

  // Loop through all categories and INSERT / UPDATE of categories first.
  $sql = "SELECT * FROM unfi_import_rcm_categories
          GROUP BY retail_dept_nm
          ORDER BY retail_dept_nm";
  $result = db_query($sql);

  // Walk the cattree.
  while($dept = $result->fetchAssoc()) {
    $dept_tid = unfi_import_rcm_categories_process_category(0, $dept['department_sid'], $dept, $vocab->vid);

    // Now all categories within that department.
    $sql = "SELECT * FROM unfi_import_rcm_categories
            WHERE department_sid = :dept
              AND retail_cat_nm != ''
            GROUP BY retail_cat_nm
            ORDER BY retail_cat_nm";
    $cats = db_query($sql, array(':dept' => $dept['department_sid'],));
    while($cat = $cats->fetchAssoc()) {
      $cat_tid = unfi_import_rcm_categories_process_category(1, $cat['category_sid'], $cat, $vocab->vid, $dept_tid);

      // Now all segments within that category.
      $sql = "SELECT * FROM unfi_import_rcm_categories
            WHERE department_sid = :dept
              AND category_sid = :cat
              AND retail_segment_nm != ''
            GROUP BY retail_segment_nm
            ORDER BY retail_segment_nm";
      $segs = db_query($sql, array(':dept' => $cat['department_sid'], ':cat' => $cat['category_sid'],));
      while($seg = $segs->fetchAssoc()) {
        $seg_tid = unfi_import_rcm_categories_process_category(2, $seg['segment_sid'], $seg, $vocab->vid, $cat_tid);

        // Now all subsegments within that segment.
        $sql = "SELECT * FROM unfi_import_rcm_categories
            WHERE department_sid = :dept
              AND category_sid = :cat
              AND segment_sid = :seg
              AND retail_subsegment_nm != ''
            GROUP BY retail_subsegment_nm
            ORDER BY retail_subsegment_nm";
        $subsegs = db_query($sql, array(':dept' => $seg['department_sid'], ':cat' => $seg['category_sid'], ':seg' => $seg['segment_sid'],));
        while($subseg = $subsegs->fetchAssoc()) {
          unfi_import_rcm_categories_process_category(3, $subseg['subsegment_sid'], $subseg, $vocab->vid, $seg_tid);

        }
      }
    }
  }

  // Unpublish any terms that are no longer present.
  $sql = "SELECT td.tid FROM taxonomy_term_data td
          INNER JOIN taxonomy_vocabulary v ON v.vid = td.vid AND v.vid = {$vocab->vid}
          LEFT JOIN field_data_field_cat_sid s ON s.entity_id = td.tid AND s.bundle = v.machine_name
          LEFT JOIN unfi_import_rcm_categories e
            ON e.department_sid = s.field_cat_sid_value
              OR e.category_sid = s.field_cat_sid_value
              OR e.segment_sid = s.field_cat_sid_value
              OR e.subsegment_sid = s.field_cat_sid_value
          WHERE s.entity_id IS NULL OR e.retail_cat_link_sid IS NULL";
  $result = db_query($sql);

  // Remove each.
  while($row = $result->fetchAssoc()) {
    taxonomy_term_delete($row['tid']);
  }

  // Update the log tables.
  unfi_import_push_to_log_tables($tables);

  // Clear cache.
  drupal_flush_all_caches();

  drupal_set_message(t($msg));
}

function unfi_import_rcm_categories_process_category($level, $sid, $row, $vid, $parent_tid=0) {
  // Make sure the level exists.
  $cur = unfi_import_rcm_categories_fetch_tid_by_sid($sid, $vid);

  if (!empty($cur)) {
    // Load the existing term for updating.
    $term = taxonomy_term_load($cur['tid']);
  }
  else {
    // Create a new term.
    $term = new stdClass();
    $term->description = '';
    $term->vid = $vid;
    $term->format = 'plain_text';
    // Add the Cat SID field for later use.
    $term->field_cat_sid = array(LANGUAGE_NONE => array(0 => array('value' => $sid)));
  }

  switch ($level) {
    case 1:
      $term->name = $row['retail_cat_nm'];
      break;
    case 2:
      $term->name = $row['retail_segment_nm'];
      break;
    case 3:
      $term->name = $row['retail_subsegment_nm'];
      break;
    default:
      $term->name = $row['retail_dept_nm'];
      break;
  }

  $term->parent = array($parent_tid);

  // Add the other fields as needed based on location in the hierarchy.
  $term->field_rcm_sid = array(LANGUAGE_NONE => array(0 => array('value' => $row['retail_cat_link_sid'])));
  $term->field_department = array(LANGUAGE_NONE => array(0 => array('value' => $row['retail_dept_nm'])));
  $term->field_profile = array(LANGUAGE_NONE => array(0 => array('value' => $row['cat_profile_nm'])));

  if ($level > 0) {
    $term->field_category = array(LANGUAGE_NONE => array(0 => array('value' => $row['retail_cat_nm'])));
  }
  if ($level > 1) {
    $term->field_segment = array(LANGUAGE_NONE => array(0 => array('value' => $row['retail_segment_nm'])));
  }
  if ($level > 2) {
    $term->field_subsegment = array(LANGUAGE_NONE => array(0 => array('value' => $row['retail_subsegment_nm'])));
  }

  taxonomy_term_save($term);

  return empty($term->tid) ? 0 : $term->tid;
}

function unfi_import_rcm_categories_fetch_tid_by_sid($sid, $vid) {
  $query = db_select('taxonomy_term_data', 'td');
  $query->fields('td', array('tid', 'name'));
  $query->join('taxonomy_vocabulary', 'v', 'v.vid = td.vid');
  $query->join('field_data_field_cat_sid', 's', 's.entity_id = td.tid AND s.bundle = v.machine_name');
  $query->condition('s.field_cat_sid_value', $sid);
  $query->condition('td.vid', $vid);
  $result = $query->execute()->fetchAssoc();

  if (!empty($result)) {
    return $result;
  }

  return 0;
}
