<?php
/**
 * @file
 * Code for the Promotions Export feature.
 */

include_once 'promotions_export.features.inc';

/**
 * Implements hook_preprocess_views_data_export().
 */
function promotions_export_preprocess_views_data_export(&$vars) {
  $view = $vars['view'];
  // If there is already a footer, prepend any views footer areas
  if (isset($vars['footer'])) {
    $footer = $vars['footer'];
  }
  else {
    $footer = '';
  }

  $empty = empty($vars['rows']);
  // NOTE: If this is a CSV the Views footer area should be CSV as well. Same
  // concept applies to other format types.
  $vars['footer'] = $view->display_handler->render_area('footer', $empty) . $footer;
}

/**
 * Implements hook_node_view
 */
function promotions_export_node_view($node, $view_mode, $langcode) {
  // Target full views of new item requests that have shipper components
  if ($view_mode == 'full' && $node->type == 'request_form') {
    // @todo Only show when Shipper Components OR Promotions exist
    $node->content['promotions_export'] = array(
      '#theme'   => 'link',
      '#text'    => t('Download all Promotions and Shipper data'),
      '#path'    => 'request/' . $node->nid . '/promotions_and_shipper_data.csv',
      '#options' => array(
        'html'       => FALSE,
        'attributes' => array(),
      ),
      '#weight' => 0,
    );
  }
}
